import pandas as pd
import o
path="Global-Inflation-Spillovers/CPI.csv"
df=pd.read_csv(path,encoding="gbk")
country_zh=["日期", "阿富汗", "阿尔巴尼亚", "阿尔及利亚", "安哥拉", "安提瓜和巴布达", "亚美尼亚", "奥地利", "阿塞拜疆", "巴哈马", "巴林", "孟加拉国", "巴巴多斯", "白俄罗斯", "比利时", "贝宁", "玻利维亚", "波斯尼亚和黑塞哥维那", "博茨瓦纳", "巴西", "文莱", "保加利亚", "布隆迪", "布基纳法索", "佛得角", "柬埔寨", "喀麦隆", "加拿大", "中非共和国", "乍得", "智利", "中国", "哥伦比亚", "刚果", "哥斯达黎加", "克罗地亚", "塞浦路斯", "捷克共和国", "丹麦", "吉布提", "多米尼克", "多米尼加共和国", "厄瓜多尔", "埃及", "萨尔瓦多", "赤道几内亚", "爱沙尼亚", "斯威士兰", "埃塞俄比亚", "斐济", "芬兰", "法国", "加蓬", "冈比亚", "格鲁吉亚", "德国", "加纳", "希腊", "格林纳达", "危地马拉", "几内亚", "几内亚比绍", "圭亚那", "海地", "洪都拉斯", "中国香港特别行政区", "匈牙利", "冰岛", "印度", "印度尼西亚", "伊朗", "伊拉克", "爱尔兰", "以色列", "意大利", "科特迪瓦", "牙买加", "日本", "约旦", "哈萨克斯坦", "肯尼亚", "基里巴斯", "科索沃", "科威特", "吉尔吉斯斯坦", "老挝", "拉脱维亚", "黎巴嫩", "莱索托", "利比里亚", "利比亚", "立陶宛", "卢森堡", "中国澳门特别行政区", "马达加斯加", "马拉维", "马来西亚", "马尔代夫", "马里", "马耳他", "毛里塔尼亚", "墨西哥", "毛里求斯", "摩尔多瓦", "蒙古", "黑山", "摩洛哥", "莫桑比克", "缅甸", "纳米比亚", "尼泊尔", "荷兰", "尼加拉瓜", "尼日尔", "尼日利亚", "马其顿", "挪威", "阿曼", "巴基斯坦", "巴拉圭", "巴拿马", "秘鲁", "菲律宾", "波兰", "葡萄牙", "卡塔尔", "罗马尼亚", "俄罗斯联邦", "卢旺达", "圣基茨和尼维斯", "圣卢西亚", "圣文森特和格林纳丁斯", "萨摩亚", "圣马力诺", "圣多美和普林西比", "沙特阿拉伯", "塞内加尔", "塞尔维亚", "塞舌尔", "塞拉利昂", "新加坡", "斯洛伐克", "斯洛文尼亚", "所罗门群岛", "南非", "韩国", "南苏丹", "西班牙", "斯里兰卡", "巴勒斯坦被占领土", "苏丹", "苏里南", "瑞典", "瑞士", "坦桑尼亚", "泰国", "东帝汶", "多哥", "汤加", "特立尼达和多巴哥", "突尼斯", "土耳其", "乌干达", "乌克兰", "阿拉伯联合酋长国", "英国", "美国", "乌拉圭", "乌兹别克斯坦", "越南", "赞比亚", "津巴布韦"]
country_en=["Date", "Afghanistan", "Albania", "Algeria", "Angola", "Antigua and Barbuda", "Armenia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Benin", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burundi", "Burkina Faso", "Cape Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Congo", "Costa Rica", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Estonia", "Swaziland", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong Special Administrative Region of China", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Côte d'Ivoire", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Lithuania", "Luxembourg", "Macao Special Administrative Region of China", "Madagascar", "Malawi", "Malaysia", "Maldives","Mali", "Malta", "Mauritania", "Mexico", "Mauritius", "Moldova", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nepal", "Netherlands", "Nicaragua", "Niger", "Nigeria", "Macedonia", "Norway", "Oman", "Pakistan", "Paraguay", "Panama", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Occupied Palestinian Territory", "Sudan", "Suriname", "Sweden", "Switzerland", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Viet Nam", "Zambia", "Zimbabwe"]
country_dict=dict(zip(country_zh,country_en))
df.rename(columns=country_dict,inplace=True)
df.to_csv('CPI_en.csv',index=False)
with open('country_dict.txt','w') as f:
    for key,value in country_dict.items():
        f.write(key+':'+value+'\n')